### ISSUE TITLE
同时管理多个账号的时候，我觉得可以在类初始化的地方 填上session.pkl文件

### ISSUE THREAD

**Issue by zxyle** [RogerLiNing/wechat_mp#3]
### 重现问题的步骤/Steps to reproduce:
1.
2.

**Comment by zxyle** [comment]
```
from wechat_mp import WeChat

EMAIL = "me@example.com"
PASSWORD = "admin"
client = WeChat(email=EMAIL, password=PASSWORD, enable_cookies=True, session="./session_1.pkl")
```

**Comment by RogerLiNing** [comment]
通过不同的session文件管理多个不同的账号确实是一个方法。但就用户操作体验而言，需要记住每个账号的session文件名，显然不是一个很好的体验。如需要在多个账号之间切换，我的建议是在session文件中直接存储多个账号的session，再通过方法进行切换。这样子用户不需要关心session文件，只需要登录多个账号之后调用方法切换即可。

**Comment by zxyle** [comment]
一个session文件 保存多个账号，确实是要更加方便

**Comment by zxyle** [comment]
问题已解决，同时发布 v1.2.0版本
